main: cz.HackerGamingCZ.HackerTools.HackerTools
author: HackerGamingCZ
version: 1.1.2
name: HackerTools
commands:
  hackertools:
    description: Main command for HackerTools
    aliases: [ht]
  debug:
    description: Debugging tool
    aliases: [htdebug]